name: RSpec

on: [push, pull_request]

jobs:
  build:
    name: "Ruby: ${{ matrix.ruby }} OS: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ruby: ["2.7", "3.0", "3.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby & Execute 'bundle install'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Test
        run: |
          ruby -v
          bin/rspec
